
# -----------------------------------------------
# 数据源 配置
# -----------------------------------------------
# 数据源
spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url:  jdbc:mysql://192.168.0.161:3306/controldb?characterEncoding=utf8&useUnicode=true&emulateLocators=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useSSL=false
  #url: jdbc:sqlite:${sqlite::resource:control.db}
  username: xctec
  password: 123456
  driverClassName: com.mysql.cj.jdbc.Driver
  hikari:
    # 始终保留在池中的最小连接数，池中的连接数量若低于此值则创建新的连接，如果连接验证失败将缩小至此值
    minimumIdle: 2
    # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    maximumPoolSize: 20
    # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，
    # 建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
    maxLifetime: 1800000
    # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
    idleTimeout: 600000
    # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
    connectionTimeout: 30000

    poolName: ControlHikariCP
    connectionTestQuery: SELECT 1
    autoCommit: true
